### PR TITLE
bind mount Elasticsearch-data to local

### PR DESCRIPTION
**Pull request by khodgkinson-he**
Create ES data directory through template and assign owner as elasticsearch.
Assign ES data bind mount directory to above (for persistence).

### CODE REVIEW

**Comment by khodgkinson-he** [comment]
..investigating "error downloading geoip database [GeoLite2-ASN.mmdb]" error occurring.

**Comment by khodgkinson-he** [comment]
..error proved to be lack of space on server (local < 10% free space) causing ES Health = RED.

**Comment by khodgkinson-he** [comment]
Instructions for reverting to volume mounts in wiki.. 

Perhaps worth a separate branch, if desired..

**Comment by aj-he** [comment]
@khodgkinson-he I think that we should have two `docker-compose-dependencies.yml` files, one with mounted data directories to persist data on the host developer machine and one that uses docker managed volumes for when it is not a requirement.

The developer can then choose which one to use depending on requirements.

Basically, I am only interested in having the data persisted if rebuilding and reloading is going to take a chunk of time - say when working on a service instance and it take a couple of hours to load and index the data. I won't want this as I do contribution feature development using a small data set.

**Comment by khodgkinson-he** [comment]
Separate persistence and non-persistence docker-compose files is the way to go!  

I'll close this PR and submit an amended version!  ^_^

**Pull request closed without merging**
